--This is the SQL code
SELECT 
    SALES_ORDERS.EID AS EmployeeID,
    SUM(ITEMS_ON_SALES_ORDERS.QTY_SOLD) AS TotalItemsSold,
    EMPLOYEES.DEPARTMENT,
    EMPLOYEES.SALARY,
    EMPLOYEES.COMMISSION_RATE
FROM 
    ITEMS_ON_SALES_ORDERS
INNER JOIN 
    SALES_ORDERS ON ITEMS_ON_SALES_ORDERS.ORDER_NO = SALES_ORDERS.ORDER_NO
INNER JOIN 
    EMPLOYEES ON SALES_ORDERS.EID = EMPLOYEES.EID
GROUP BY 
    SALES_ORDERS.EID
ORDER BY 
    TotalItemsSold DESC
LIMIT 10;